config/routes.rb
Rails.application.routes.draw do

  devise_for :admins, controllers: {
    sessions:      'admin/admins/sessions',
    passwords:     'admin/admins/passwords',
    registrations: 'admin/admins/registrations'
  }

  namespace :admin do

   get "/" => "homes#top"
   resources :customers,only: [:index,:show,:edit,:update]
   resources :genres,only: [:index,:create,:edit,:update]
   resources :items, except: [:destroy]
   resources :orders,only: [:show,:update]
   resources :order_details,only: [:update]
 end


 devise_for :customers, controllers: {
   sessions:      'public/customers/sessions',
   passwords:     'public/customers/passwords',
   registrations: 'public/customers/registrations'
 }

 root to: "public/homes#top"
 get "/about" => "public/homes#about"

  scope module: :public do
   get "/customers/my_page" => "customers#show"
   get '/customers/confirm' => 'customers#confirm'
   patch '/customers/withdraw' => 'customers#withdraw'
   resources :customers,only: [:show,:edit,:update]
   delete '/cart_items/destroy_all' => 'cart_items#destroy_all'
   resources :cart_items,only: [:index,:create,:update,:destroy]
   resources :items, only: [:index,:show]
   resources :orders,only: [:new,:index,:show,:create] do
    collection do
     get :thanks
     post :confirm
    end
   end

   resources :addresses,except: [:show,:new]
 end




  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer
  
  validates :name, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true
  
  def full_address
    "〒" + " " + self.postal_code + " " + self.address + " " + self.name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :item
  belongs_to :customer
  validates :amount, presence: true
  
  
  
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :cart_items, dependent: :destroy
  has_many :addresses, dependent: :destroy
  has_many :orders, dependent: :destroy
  
validates :first_name, presence: true
validates :last_name, presence: true
validates :first_name_kana, presence: true
validates :last_name_kana, presence: true
validates :postal_code, presence: true
validates :telephone_number, presence: true
validates :address, presence: true
validates :email, presence: true


  def full_name
    self.last_name + " " + self.first_name
  end

  def full_address
    "〒" + " " + self.postal_code + " " + self.address
  end
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items, dependent: :destroy

  validates :name, presence: true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :genre
  has_many :cart_items, dependent: :destroy
  has_many :order_details, dependent: :destroy
  attachment :image
  
  validates :name, presence: true
  validates :introduction, presence: true
  
  def with_tax_price
    (price * 1.1).floor
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details, dependent: :destroy



  enum payment_method:{
    credit_card:     0, #クレジットカード
    bank_transfer:   1, #銀行振込
  }



  enum status:{
    waiting_for_payment:     0, #入金待ち
    payment_confirmation:    1, #入金確認
    production:              2, #製作中
    reade_to_ship:           3, #発送準備中
    sent:                    4, #発送済み
  }

  def full_address
    "〒" + " " + self.postal_code + " " + self.address
  end
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item
  
  
  enum making_status:{
    not_startable:             0, #着手不可
    waiting_for_production:    1, #製作待ち
    production:                2, #製作中
    production_completed:      3, #製作完了
  }
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  def index
    @customers = Customer.all
    @customers = Customer.page(params[:page]).per(10)
  end


  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])

  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      redirect_to admin_customer_path(@customer.id)
    else
     render :edit
    end

  end

  def customer_params
    params.require(:customer).permit(:first_name,:last_name,:first_name_kana,:last_name_kana,:email,:postal_code,:address,:telephone_number,:is_active)
  end

end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def index
    @genres = Genre.all
    @genre = Genre.new
  end


  def create
   @genre = Genre.new(genre_params)
    if @genre.save
      redirect_to admin_genres_path
    else
     @genres = Genre.all
      render :index
    end
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      redirect_to admin_genres_path
    else
     render :edit
    end
  end

  private
  def genre_params
     params.require(:genre).permit(:name)

  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @orders = Order.all
    @orders = Order.page(params[:page]).per(10)
  end

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def index
    @items = Item.all
    @items = Item.page(params[:page]).per(10)
  end

  def show
    @item = Item.find(params[:id])
  end

  def new
    @item = Item.new
    @genres = Genre.all
  end

  def create
   @item = Item.new(item_params)
    if @item.save
      redirect_to admin_item_path(@item.id)
    else
     @items = Item.all
      render :new
    end
  end

  def edit
    @item = Item.find(params[:id])
    @genres = Genre.all
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admin_item_path(@item.id)
    else

     render :edit
    end
  end

  def item_params
    params.require(:item).permit(:name, :image, :introduction, :price, :is_active, :genre_id)
  end
end

app/controllers/admin/order_details_controller.rb
class Admin::OrderDetailsController < ApplicationController
  def update
    @order_detail = OrderDetail.find(params[:id])
    @order_detail.update(order_detail_params)
    redirect_to admin_order_path(@order_detail.order.id)
  end
  
  private
  def order_detail_params
     params.require(:order_detail).permit(:making_status)
  end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def show
    @order = Order.find(params[:id])
   
  end

  def update
    @order = Order.find(params[:id])
    @order.update(order_params)
    redirect_to admin_order_path(@order.id)
  end

  def order_params
     params.require(:order).permit(:status)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  before_action :configure_permitted_parameters, if: :devise_controller?




  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name,:last_name,:first_name_kana,:last_name_kana,:email,:postal_code,:address,:telephone_number])
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/customers/edit.html.erb
<p id="notice"></p>
  <div class="container">
    <div class="row">
      <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
        <h1>の会員情報編集</h1>
        
          <%= form_with model: @customer,url: admin_customer_path, local:true do |f| %>

          <div class="form-group">
            <label for="id">会員ID</label>
            <%= f.text_field :id, class:"form-control id" %>
          </div>

          <div class="form-group">
            <label for="name">氏名</label>
            <%= f.text_field :last_name, class:"form-control name" %>
            <%= f.text_field :first_name, class:"form-control name" %>
          </div>
          <div class="form-group">
            <label for="name">フリガナ</label>
            <%= f.text_field :last_name_kana,  class:"form-control name" %>
            <%= f.text_field :first_name_kana,  class:"form-control name" %>
          </div>

          <div class="form-group">
            <label for="postal_code">郵便番号</label>
            <%= f.text_field :postal_code, class:"form-control postal_code" %>
          </div>
          <div class="form-group">
            <label for="address">住所</label>
            <%= f.text_field :address, class:"form-control address" %>
          </div>
          <div class="form-group">
            <label for="telephone_number">電話番号</label>
            <%= f.text_field :telephone_number, class:"form-control telephone_number" %>
          </div>
          <div class="form-group">
            <label for="email">メールアドレス</label>
            <%= f.text_field :email, class:"form-control email" %>
          </div>


          <div class="form-group">
            <label for="status">会員ステータス</label>
            <%= f.radio_button :is_active, :true %>
            <%= f.label :is_active, "有効", {value: :true, style: "display: inline-block;"} %>
            <%= f.radio_button :is_active, :false %>
            <%= f.label :is_active, "退会", {value: :false, style: "display: inline-block;"} %>
          </div>
          <div class="form-group">
            <%= f.submit "変更を保存", class:"btn btn-success" %>
          </div>
          <% end %>
       
      </div>
   </div>
 </div>

app/views/admin/customers/index.html.erb
<p id="notice"></p>
  <div class="container">
      <div class="row">
          <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
              <h1>会員一覧</h1>

              <table class = "table">
                   <thead>
                       <tr>
                           <th>会員ID</th>
                           <th>氏名</th>

                           <th>メールアドレス</th>
                           <th>ステータス</th>
                       </tr>
                 </thead>
                 <tbody>
                     <% @customers.each do |customer| %>
                     <tr class="customer-box">
                         <td><%= customer.id %></td>
                         <td><%= link_to customer.full_name, admin_customer_path(customer.id)%></td>
                         <td><%= customer.email %></td>
                         <% if customer.is_active == true %>
                         <td><%= "有効" %></td>
                         <% else %>
                         <td><%= "退会" %></td>
                         <% end %>
                     </tr>
                     <% end %>
                  </tbody>
              </table>
            <%= paginate @customers, theme: 'twitter-bootstrap-4' %>
          </div>
      </div>
 </div>

app/views/admin/customers/show.html.erb
<div class = "container">
 <h2><%= @customer.full_name %>さんの会員詳細</h2>

    <table class="table table-hover table-inverse">
      <tbody>
        <tr class="customer-box">
           <td>会員</td>
           <td>
             <%= @customer.id %>
           </td>
        </tr>

        <tr>
           <td>名前</td>
           <td>
             <%= @customer.full_name %>
           </td>
        </tr>

        <tr>
           <td>フリガナ</td>
           <td>
             <%= @customer.last_name_kana %>
             <%= @customer.first_name_kana %>
           </td>
        </tr>

        <tr>
           <td>郵便番号</td>
           <td>
             <%= @customer.postal_code %>
           </td>
        </tr>

        <tr>
           <td>住所</td>
           <td>
             <%= @customer.address %>
           </td>
        </tr>

        <tr>
           <td>電話番号</td>
           <td>
             <%= @customer.telephone_number %>
           </td>
        </tr>

        <tr>
           <td>メールアドレス</td>
           <td>
             <%= @customer.email %>
           </td>
        </tr>

        <tr>
           <td>会員ステータス</td>
           <% if @customer.is_active == true %>
           <td><%= "有効" %></td>
           <% else %>
           <td><%= "退会" %></td>
           <% end %>
         </tr>
      </tbody>
    </table>
    <%= link_to "編集する", edit_admin_customer_path, class:"btn btn-sm btn-success" %>

    <%= link_to "注文履歴一覧を見る", admin_path, class:"btn btn-sm btn-primary" %>
 </div>

app/views/admin/genres/edit.html.erb
<p id="notice"></p>
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h1>ジャンル編集</h1>
      <%= form_with model:@genre,url: admin_genre_path, local: true do |f| %>
      <tr>
        <div class="form-group">
         <label for="genre_name">ジャンル名</label>
         <%= f.text_field :name, class:"form-control genre_name"%>
        </div>
        
        <div class="form-group">
          <%= f.submit "変更を保存",  class:"btn btn-success"%>
        </div>
      </tr>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/genres/index.html.erb
<p id="notice"></p>
  <div class="container">
    <div class="row">
      <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto"><p id="notice"></p>
      <h1>ジャンル一覧・追加</h1>
      <table>
        <%= form_with model: @genre,url: admin_genres_path, local:true do |f| %>
        <tr>
          <div class="form-group">
            <label for="name">ジャンル名</label>
            <%= f.text_field :name, class:"form-control name" %>
          </div>

          <div class="form-group">
            <%= f.submit "新規登録", class:"btn btn-secondary" %>
          </div>
        </tr>
        <% end %>
        <thead>
          <tr>
            <th>ジャンル</th>
            <th colspan="3"></th>
          </tr>
    　   </thead>
    　   <tbody>
    　     <% @genres.each do |genre| %>
    　     <tr class="genre-box">
            <td><%= genre.name %></td>
            <td><%= link_to "編集する", edit_admin_genre_path(genre.id), class:"btn btn-sm btn-success" %></td>
          </tr>
          <% end %>
         </tbody>
       </table>
      </div>
   </div>
 </div>

app/views/admin/items/edit.html.erb
  <div class="container">
    <div class="row">
      <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
        <h1>商品新規登録</h1>

          <%= form_with model: @item,url: admin_item_path(@item.id), local:true do |f| %>
          <div class="form-group">
            <label for="image">商品画像</label>
            <%= f.attachment_field :image, placeholder: "画像", class:"form-control-file image" %>
          </div>
          <div class="form-group">
            <label for="name">商品名</label>
            <%= f.text_field :name, class:"form-control name" %>
          </div>
          <div class="form-group">
            <label for="introduction">商品説明</label>
            <%= f.text_field :introduction, class:"form-control introduction" %>
          </div>
          <div class="form-group">
            <label for="genre">ジャンル</label>
            <%= f.collection_select(:genre_id, @genres, :id, :name) %>
          </div>

          <div class="form-group">
            <label for="price">税抜価格</label>
            <div class = "row">
            <div class = "col-md-6" >
             <%= f.text_field :price, class:"form-control price" %>
            </div>
            <div class = "col-md-6" >
              円
            </div>
            </div>
          </div>

          <div class="form-group">
            <label for="status">販売ステータス</label>
            <%= f.radio_button :is_active, :true , checked: "checked" %>
            <%= f.label :is_active, "販売中", {value: :true, style: "display: inline-block;"} %>
            <%= f.radio_button :is_active, :false %>
            <%= f.label :is_active, "反映停止", {value: :false, style: "display: inline-block;"} %>
          </div>
          <div class="form-group">
            <%= f.submit "変更内容を保存", class:"btn btn-secondary" %>
          </div>
          <% end %>

      </div>
    </div>
  </div>

app/views/admin/items/index.html.erb
<div class="container">
      <div class="row">
         <div class = "row">
          <div class = "col-md-6" >
              <h1>商品一覧</h1>
          </div>
          <div class = "col-md-6" >
              <td><%= link_to "＋", new_admin_item_path, class:"btn btn-primary rounded-circle "%></td>
          </div>
              <table class = "table table-bordered">
                   <thead>
                       <tr>
                           <th>商品ID</th>
                           <th>商品名</th>
                           <th>税抜価格</th>
                           <th>ジャンル</th>
                           <th>ステータス</th>
                       </tr>
                 </thead>
                 <tbody>
                     <% @items.each do |item| %>
                     <tr class="item-box">
                         <td><%= item.id %></td>
                         <td><%= link_to item.name, admin_item_path(item.id)%></td>
                         <td><%= item.price %></td>
                         <td><%= item.genre.name %></td>
                         <% if item.is_active == true %>
                         <td><%= "販売中" %></td>
                         <% else %>
                         <td><%= "停止" %></td>
                         <% end %>
                     </tr>
                     <% end %>
                  </tbody>
              </table>


                 <%= paginate @items, theme: 'twitter-bootstrap-4' %>



      </div>
 </div>

app/views/admin/items/new.html.erb
<p id="notice"></p>
  <div class="container">
    <div class="row">
      <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
        <h1>商品新規登録</h1>
        <%= form_with model: @item,url: admin_items_path, local:true do |f| %>
        <table>
          <div class="form-group">
            <label for="image">商品画像</label>
            <%= f.attachment_field :image, placeholder: "画像", class:"form-control-file image" %>
          </div>

          <div class="form-group">
            <label for="name">商品名</label>
            <%= f.text_area :name, class:"form-control name" %>
          </div>
          <div class="form-group">
            <label for="introduction">商品説明</label>
            <%= f.text_field :introduction, class:"form-control introduction" %>
          </div>
          <div class="form-group">
            <label for="genre">ジャンル</label>
            <%= f.collection_select(:genre_id, @genres, :id, :name) %>
          </div>
          <div class="form-group">
            <label for="price">税抜価格</label>
            <div class = "row">
            <div class = "col-md-6" >
             <%= f.text_field :price, class:"form-control price" %>
            </div>
            <div class = "col-md-6" >
              円
            </div>
            </div>
          </div>
          <div class="form-group">
            <label for="status">販売ステータス</label>
            <%= f.radio_button :is_active, :true , checked: "checked" %>
            <%= f.label :is_active, "販売中", {value: :true, style: "display: inline-block;"} %>
            <%= f.radio_button :is_active, :false %>
            <%= f.label :is_active, "販売停止", {value: :false, style: "display: inline-block;"} %>
          </div>
          <div class="form-group">
            <%= f.submit "新規登録", class:"btn btn-secondary" %>
          </div>
        </table>
        <% end %>
      </div>
   </div>
 </div>

app/views/admin/items/show.html.erb
 <div class="container">
    <div class="row">
      <div class="col-md-5">
        <%= attachment_image_tag @item, :image, :fill, 300, 300, format: 'jpeg', class:"attachment image fallback" %>
     </div>
     <div class="col-md-5 ">
        <h2>商品一覧</h2>
        <table class="table table-hover table-inverse">
      <tbody>
         <tr class="item-box">
           <td>商品名</td>
           <td><%= @item.name %></td>
         </tr>
         <tr class="item-box">
           <td>商品説明</td>
           <td><%= @item.introduction %></td>
         </tr>
         <tr class="item-box">
           <td>ジャンル</td>
           <td><%= @item.genre.name %></td>
         </tr>
         <tr class="item-box">
           <td>税込価格<br>(税抜価格)</td>
           <td><%= @item.with_tax_price %>(<%= @item.price %>)</td>
         </tr>
         <tr class="item-box">
           <td>販売ステータス</td>
           <% if @item.is_active == true %>
           <td><%= "販売中" %></td>
           <% else %>
           <td><%= "販売停止" %></td>
           <% end %>
         </tr>
        <td><%= link_to "編集する", edit_admin_item_path(@item.id), class:"btn btn-sm btn-success" %></td>
      </tbody>
    </table>
 </div>
 </div>
 </div>

app/views/admin/orders/show.html.erb
  <div class="container">
      <div class="row">

              <h1>会員一覧</h1>

              <table class = "table table-bordered">
                   <thead>
                       <tr>
                           <th>購入者</th>
                           <th>注文日</th>
                           <th>配送先</th>
                           <th>支払方法</th>
                           <th>注文ステータス</th>
                       </tr>
                 </thead>
                 <tbody>
                     <tr class="order-box">
                         <td><%= link_to @order.name, admin_customer_path(@order.customer_id)%></td>
                         <td><%= @order.created_at.strftime("%Y-%m-%d %H:%M") %></td>
                         <td><%= @order.full_address %><br><%= @order.name %></td>
                         <td><%= @order.payment_method_i18n %></td>
                         
                         <td>
                           <%= form_with model: @order,url: admin_order_path(@order.id), local:true do |f| %>
                           <%= f.select :status, Order.statuses.map { |k, v| [t("enums.order.status.#{k}"), k]} %>
                           <%= f.submit "更新", class:"btn btn-secondary" %>
                           <% end %>
                         </td>
                         
                     </tr>
                  </tbody>
              </table>
          <div class="container">
            <div class = "row">
              <div class = "col-md-9 " >

             <table class = "table table-bordered">
               <thead>
                 <tr>
                   <th>商品名</th>
                   <th>単価（税込）</th>
                   <th>数量</th>
                   <th>小計</th>
                   <th>製作ステータス</th>
                 </tr>
              </thead>
              <tbody>
                 <% @order.order_details.each do |order_detail|%>
                     <tr class="cart_item-box">
                       <td><%= order_detail.item.name %></td>
                       <td><%= order_detail.price %></td>
                       <td><%= order_detail.amount %></td>
                       <td><%= order_detail.price*order_detail.amount %></td>


                       <td>
                         <%= form_with model: order_detail,url: admin_order_detail_path(order_detail.id), local:true do |f| %>
                         <%= f.select :making_status, OrderDetail.making_statuses.map { |k, v| [t("enums.order_detail.making_status.#{k}"), k]} %>
                         <%= f.submit "更新", class:"btn btn-secondary" %>
                         <% end %>
                       </td>

                     </tr>
                    
                <% end %>
              </tbody>
             </table>
             </div>

              <div class = "col-md-2" >
              <table class = "table table-bordered">
                 <tbody>
                     <tr>
                       <td>商品合計</td>
                       <td><%= @order.total_payment %></td>
                     </tr>
                     <tr>
                       <td>送料</td>
                       <td><%= @order.postage %></td>
                     </tr>
                     <tr>
                       <td>商品金額合計</td>
                       <td><%= @order.total_payment + @order.postage %></td>
                     </tr>


                     </tr>
                  </tbody>
                </table>
              </div>
              </div>
              </div>



          </div>

 </div>